dist: bionic
language: python
python:
    - "3.6"
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install -r optional-requirements.txt
script:
    - pytest --cov=./

after_success:
    - codecov