dist: bionic
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install poetry
    - pip install pytest-cov
install:
    - poetry build
    - poetry install
    - pip install fireworks-ml
script:
    - pytest --cov=./
    # Add scripts for linting
after_success:
    - codecov